version: '3'

services:
  api-gateway:
    image: traefik:v2.6
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # TODO: remove
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.internal`)"

  s3:
    image: minio/minio
    labels:
      - "traefik.http.routers.s3.rule=Host(`s3.docker.internal`)"
      - "traefik.http.services.s3.loadbalancer.server.port=9000"
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server --address 0.0.0.0:9000 /data

  redis-prov:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning

  redis-cont:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning

  grafana:  
    image: grafana/grafana-enterprise:8.2.0
    ports:
      - 3000:3000
    user: '104'

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9000:9090
